input_data_path: "data/heart_cleveland_upload.csv"
input_test_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/model_RF.pkl"
path_for_predicts: "data/predictions_RF.csv"
metric_path: "models/metrics_RF.json"
splitting_params:
  val_size: 0.2
  random_state: 18
train_params:
  random_state: 18
  model_type: "RandomForestClassifier"
feature_params:
  numerical_features:
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
    - "condition"
  target: "condition"
