input_data_path: "data/heart_cleveland_upload.csv"
input_test_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
path_for_predicts: "data/predictions.csv"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.1
  random_state: 42
train_params:
  random_state: 42
  max_iter: 1000
  model_type: "LogisticRegression"
feature_params:
  numerical_features:
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
    - "condition"
  target: "condition"
